import Image from "next/image";
import Link from "next/link";
import { events, fallbackImages, games, promotions, siteSettings } from "@/lib/content";

export const dynamic = "force-dynamic";
export default async function Home() { const [settings, gameItems, promoItems, eventItems] = await Promise.all([siteSettings(), games(), promotions(), events()]); return <main>
  <section className="hero"><Image className="hero-image" src={fallbackImages.hero} alt="Elegant casino table at 86 Casino" fill priority sizes="100vw"/><div className="container hero-content"><div className="eyebrow light">Luxury gaming · unforgettable nights</div><h1>Accra&apos;s Destination for<br/><em>Gaming &amp; Entertainment</em></h1><p className="hero-copy">A new rhythm for nights out in Accra. Discover considered hospitality, classic games and a room made for memorable evenings.</p><div className="hero-actions"><Link className="button button-red" href="/visit">Visit 86 Casino</Link><Link className="button button-outline" href="/casino">Explore the casino</Link></div></div></section>
  <section className="section light honeycomb"><div className="container"><div className="section-heading"><div><div className="eyebrow">The casino</div><h2>Find your game.</h2></div><p>From timeless table games to a little more sparkle, settle into an experience with its own energy.</p></div><div className="cards">{gameItems.map((game, i) => <article className="game-card" key={game.id}><Image src={game.image} alt={game.name} width={600} height={420}/><div className="game-card-body"><div className="card-number">0{i + 1}</div><h3>{game.name}</h3><p>{game.subtitle}</p></div></article>)}</div></div></section>
  <section className="section red-section honeycomb-dark"><div className="container"><div className="section-heading"><div><div className="eyebrow light">At 86</div><h2>Make it a night.</h2></div><p style={{color:"#edcfd1"}}>There is always another reason to stay a little longer. Explore what is happening now.</p></div><div className="promo-grid">{promoItems.slice(0,3).map(promo => <article className="promo-card" key={promo.id}><Image src={promo.image} alt={promo.title} width={700} height={440}/><div className="promo-card-body"><div className="eyebrow light">{promo.subtitle}</div><h3>{promo.title}</h3><p>{promo.description}</p><Link className="button button-outline" href="/promotions">Discover more</Link></div></article>)}</div></div></section>
  <section className="vip-section"><Image className="vip-image" src={fallbackImages.lounge} alt="The 86 Casino VIP lounge" width={1000} height={800}/><div className="vip-copy light honeycomb"><div><div className="eyebrow">VIP experience</div><h2>Known by name.<br/>Remembered.</h2><p>For guests who like their evenings to feel effortless. Speak with our team about a more personal way to experience 86.</p><Link className="button button-dark" href="/vip">Discover VIP</Link></div></div></section>
  <section className="section light honeycomb"><div className="container"><div className="section-heading"><div><div className="eyebrow">What&apos;s on</div><h2>Good nights ahead.</h2></div><Link className="button button-outline-dark" href="/events">View all events</Link></div><div className="event-grid">{eventItems.slice(0,3).map(event => <article className="event-card" key={event.id}><Image src={event.image} alt={event.title} width={700} height={440}/><div className="event-card-body"><div className="event-date">{new Date(event.dateTime).toLocaleDateString("en-GH", { month:"short", day:"numeric" })} · {event.subtitle}</div><h3>{event.title}</h3><p>{event.description}</p></div></article>)}</div></div></section>
  <section className="section light"><div className="container visit-grid"><div><div className="eyebrow">Find us</div><h2>Make your<br/>way to 86.</h2><div className="detail-list"><div className="detail"><strong>Location</strong><span>{settings.address}</span></div><div className="detail"><strong>Hours</strong><span>{settings.hours}</span></div><div className="detail"><strong>Contact</strong><span>{settings.phone}<br/>{settings.email}</span></div></div><a className="button button-dark" href={settings.directions}>Get directions</a></div><Image className="visit-image" src={fallbackImages.exterior} alt="86 Casino exterior" width={1000} height={800}/></div></section>
</main>; }