import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/db";

const resources = ["games", "promotions", "events", "gallery", "pages"] as const;
type Resource = typeof resources[number];
function model(resource: Resource) { return { games: "game", promotions: "promotion", events: "event", gallery: "galleryItem", pages: "page" }[resource]; }
function clean(resource: Resource, input: Record<string, unknown>) {
  const allowed = resource === "games" ? ["name", "subtitle", "description", "image", "sortOrder", "active"] : resource === "promotions" ? ["title", "subtitle", "description", "image", "terms", "startDate", "endDate", "featured", "active", "sortOrder"] : resource === "events" ? ["title", "subtitle", "description", "image", "dateTime", "active", "sortOrder"] : resource === "gallery" ? ["image", "altText", "category", "caption", "sortOrder", "active"] : ["slug", "title", "eyebrow", "intro", "body", "heroImage", "seoTitle", "seoDescription", "published"];
  return Object.fromEntries(allowed.filter(key => input[key] !== undefined).map(key => [key, input[key]]));
}
export async function GET(_request: Request, { params }: { params: Promise<{resource:string}> }) { if (!(await requireAdmin())) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { resource } = await params; if (!resources.includes(resource as Resource)) return NextResponse.json({ error: "Unknown collection" }, { status: 404 }); const client = prisma as unknown as Record<string, { findMany: (args: unknown) => Promise<unknown> }>; return NextResponse.json(await client[model(resource as Resource)].findMany({ orderBy: { createdAt: "desc" } })); }
export async function POST(request: Request, { params }: { params: Promise<{resource:string}> }) { if (!(await requireAdmin())) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { resource } = await params; if (!resources.includes(resource as Resource)) return NextResponse.json({ error: "Unknown collection" }, { status: 404 }); const data = clean(resource as Resource, await request.json()); const client = prisma as unknown as Record<string, { create: (args: unknown) => Promise<unknown> }>; return NextResponse.json(await client[model(resource as Resource)].create({ data })); }
export async function PATCH(request: Request, { params }: { params: Promise<{resource:string}> }) { if (!(await requireAdmin())) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { resource } = await params; if (!resources.includes(resource as Resource)) return NextResponse.json({ error: "Unknown collection" }, { status: 404 }); const input = await request.json(); if (!input.id) return NextResponse.json({ error: "An id is required" }, { status: 400 }); const client = prisma as unknown as Record<string, { update: (args: unknown) => Promise<unknown> }>; return NextResponse.json(await client[model(resource as Resource)].update({ where: { id: input.id }, data: clean(resource as Resource, input) })); }
export async function DELETE(request: Request, { params }: { params: Promise<{resource:string}> }) { if (!(await requireAdmin())) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { resource } = await params; if (!resources.includes(resource as Resource)) return NextResponse.json({ error: "Unknown collection" }, { status: 404 }); const input = await request.json(); if (!input.id) return NextResponse.json({ error: "An id is required" }, { status: 400 }); const client = prisma as unknown as Record<string, { delete: (args: unknown) => Promise<unknown> }>; await client[model(resource as Resource)].delete({ where: { id: input.id } }); return NextResponse.json({ ok: true }); }